# ref. Mortimer S. 271
$$
\begin{align}
HA + H2O & \rightleftharpoons H3O(+) + A(-) & K= & 1.75\times 10^{-5} \\
2 H2O & \rightleftharpoons H3O(+) + OH(-) & K= & 10^{-14}
\end{align} \\
$$
<pre>
```
| i | comp. | m0, mol/g |
|---|-------|-----------|
|0|H2O	|	0.05555
|1|HA	|	0.000100
|2|A(-)	|	0.0
|3|H3O(+)|	1.0E-10
|4|HO(-)|	1.0E-10
```
</pre>
$$x = [n_0 m_1 m_2 m_3 m_4 \xi_1 \xi_2 \gamma_0 \gamma_1 \gamma_3 \gamma_4]$$

In [2]:
from sympy import *
import numpy as np
init_printing(use_unicode = True)
eps = np.finfo(float).eps
mm0 = 2*1.00794+15.9994
m0_ref = 1/1000.0
x, n0, m1, m2, m3, m4 = symbols('x n0 m1 m2 m3 m4')
xi1, xi2 = symbols('xi1 xi2')
g0, g1, g2, g3, g4 = symbols('g0 g1 g2 g3 g4')
i = symbols('i')
# X0 = (55.5486293302,0.0000985577634614,0.00000136987783435,0.0000013698778423,7.94928842737e-15,
#       0.00137086977796, -9.99920449554e-08,
#       0.998176760953, 1.00031547577, 0.959416637324, 0.959416637324, 0.959416637324, 
#       0.0000013698778423) #1/2.0*(0.0 + 10e-10*(+1)**2 + 10e-10*(-1)**2)
# X0 = (5.55486633e+01,   9.85916194e-05,   1.33596083e-06,
#            1.33596083e-06,   7.20160179e-15,   1.33692903e-03,
#           -9.99927932e-08,   1.00000000e+00,   1.00000000e+00,
#            1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
#            1.33596083e-06)
X0 = (5.55500000e+01,   9.99251756e-05,   2.21878461e-26,
           9.99251756e-11,   9.99251756e-11,   0.00000000e+00,
           0.00000000e+00,   1.00000000e+00,   1.00000000e+00,
           1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
           9.99251756e-11)
X = (n0, m1, m2, m3, m4,
     xi1, xi2,
     g0, g1, g2, g3, g4, i)
Q1 = 1 * g0**-1 * g1**-1 * g2**1 * g3**1 * g4**0 * \
        (1/mm0)**-1 * m1**-1 * m2**1 * m3**1 * m4**0 * \
        (1/m0_ref)**(-1-1+1+1+0)
Q2 = 1 * g0**-2 * g1**0 * g2**0 * g3**1 * g4**1 * \
        (1/mm0)**-2 * m1**0 * m2**0 * m3**1 * m4**1 * \
        (1/m0_ref)**(-2+0+0+1+1)
f_0 = (
    -n0 + 0.05555*1000 - 2*xi2 - 1*xi1,
    -m1*n0*mm0 + 0.0001*(0.05555*1000)*mm0 -xi1,
    -m2*n0*mm0 + 0*(0.05555*1000)*mm0 +xi1,
    -m3*n0*mm0 + 1.0E-10*(0.05555*1000)*mm0 +xi1 + xi2,
    -m4*n0*mm0 + 1.0E-10*(0.05555*1000)*mm0 + xi2,
    -10**-4.75696195131371/(997/mm0) + Q1,
    -10**-14/(997/mm0)**2 + Q2,
    -g0 + exp(-1.0*mm0*(m1+ m2 + m3 + m4)),
    -g1 + 10**(0.1*i/m0_ref),
    -g2 + 10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)),
    -g3 + 10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)),
    -g4 + 10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)),
    -i + 1/2.0*(m2*(-1)**2 + m3*(+1)**2 + m4*(-1)**2)
    )
j_8_2 = -1.0*mm0*exp(-1.0*mm0*(m1 + m2 + m3 + m4))
j_8_3 = j_8_2
j_8_4 = j_8_2
j_8_5 = j_8_2
factor_1 = (sqrt(i)/(1 + sqrt(i))-0.3*i)
dfactor_1_di = (1/(2 * sqrt(i) * (1 + sqrt(i))**2)-0.3) 
j_9_13 =  0.1*10**(-0.1*i)
j_10_13 = (-0.510*log(10.0)*(-1)**2*dfactor_1_di) * \
          10**(-0.510*(-1)**2*factor_1)
j_11_13 = (-0.510*log(10.0)*(+1)**2*dfactor_1_di) * \
          10**(-0.510*(+1)**2*factor_1)
j_12_13 = (-0.510*log(10.0)*(-1)**2*dfactor_1_di) * \
          10**(-0.510*(-1)**2*factor_1)

J = Matrix((
    (-1, 0, 0, 0, 0,            -1, -2, 0, 0, 0, 0, 0, 0),
    (-m1*mm0, -n0*mm0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0),
    (-m2*mm0, 0, -n0*mm0, 0, 0, +1, 0, 0, 0, 0, 0, 0, 0),
    (-m3*mm0, 0, 0, -n0*mm0, 0, +1, +1, 0, 0, 0, 0, 0, 0),
    (-m4*mm0, 0, 0, 0, -n0*mm0,  0, +1, 0, 0, 0, 0, 0, 0),
    (0,             -1/m1*Q1, +1/m2*Q1, +1/m3*Q1,  0/m4*Q1, 0, 0, 
        -1/g0*Q1,   -1/g1*Q1, +1/g2*Q1, +1/g3*Q1,  0/g4*Q1, 0),
    (0,              0/m1*Q2,  0/m2*Q2, +1/m3*Q2, +1/m4*Q2, 0, 0, 
        -2/g0*Q1,    0/g1*Q2,  0/g2*Q2, +1/g3*Q1, +1/g4*Q2, 0),
    (0,  j_8_2, j_8_3, j_8_4, j_8_5, 0, 0, 
                          -1, 0, 0, 0, 0, 0),
    (0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, j_9_13),
    (0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, j_10_13),
    (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, j_11_13),
    (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, j_12_13),
    (0, 0, 1/2.0*(-1)**2, 1/2.0*(+1)**2, 1/2.0*(-1)**2, 
                    0, 0, 0, 0, 0, 0, 0, -1)
    ))
solution = nsolve(f_0, X, X0, verbose=True)

f(x):
Matrix([[-n0 - xi1 - 2*xi2 + 55.55, -18.01528*m1*n0 - xi1 + 0.1000748804, -18.01528*m2*n0 + xi1, -18.01528*m3*n0 + xi1 + xi2 + 1.000748804e-7, -18.01528*m4*n0 + xi2 + 1.000748804e-7, -3.1621604814443e-7 + 18.01528*g2*g3*m2*m3/(g0*g1*m1), -3.26506413401086e-18 + 324.5503134784*g3*g4*m3*m4/g0**2, -g0 + exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), 10**(100.0*i) - g1, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i) - g2, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i) - g3, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i) - g4, -i + 0.5*m2 + 0.5*m3 + 0.5*m4]])
J(x):
Matrix([[-1, 0, 0, 0, 0, -1, -2, 0, 0, 0, 0, 0, 0], [-18.01528*m1, -18.01528*n0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0], [-18.01528*m2, 0, -18.01528*n0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [-18.01528*m3, 0, 0, -18.01528*n0, 0, 1, 1, 0, 0, 0, 0, 0, 0], [-18.01528*m4, 0, 0, 0, -18.01528*n0, 0, 1, 0, 0, 0, 0, 0, 0], [0, -18.01528*g2*g3*m2*m3/(g0*


[                       -1.0                          0.0                          0.0                         0.0                        0.0  -1.0  -2.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[ -0.00180018001748316802487      -1000.74880399999998359                          0.0                         0.0                        0.0  -1.0   0.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-3.99720260088408023268e-25                          0.0      -1000.74880399999998359                         0.0                        0.0   1.0   0.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[  -1.8001800174831681429e-9     


[                      -1.0                         0.0                         0.0                         0.0                        0.0  -1.0  -2.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-0.00180014232176599867472     -1000.74880399300519057                         0.0                         0.0                        0.0  -1.0   0.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-3.76958904438531323652e-8                         0.0     -1000.74880399300519057                         0.0                        0.0   1.0   0.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-2.06516200191884637342e-8               

 [       55.5499904075736740655]
[  0.0000999135902178413069929]
[    1.16052151365006912175e-8]
[    1.06951575971707503562e-8]
[  -9.10057539329940839053e-10]
[  0.0000116139038995078229171]
[-0.00000101073878820775740229]
[       0.99999976530998152866]
[        1.0000024396448301495]
[      0.994548050581134113023]
[      0.994548050581134113023]
[      0.994548050581134113023]
[    1.06951575971707503562e-8]
error: 0.00179850229617444662701
Jx:
[                      -1.0                         0.0                        0.0                        0.0                           0.0  -1.0  -2.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-0.00179997130357967220363     -1000.74863118975389372                        0.0                        0.0                           0.0  -1.0   0.0                          0.0                          0.0                 


[                      -1.0                         0.0                        0.0                         0.0                           0.0  -1.0  -2.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-0.00179988799885350906593     -1000.74853206900520318                        0.0                         0.0                           0.0  -1.0   0.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[ -2.9263649955499812962e-7                         0.0    -1000.74853206900520318                         0.0                           0.0   1.0   0.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[ -2.8398221693379547542e-7         

 [      55.549975576135476471]
[ 0.000099900103778251247778]
[  2.51365996813787476318e-8]
[  2.48710241000629938855e-8]
[-2.65575581315753724102e-10]
[0.0000251554129956546136384]
[ -3.65774237483868056116e-7]
[    0.999999058935312117589]
[     1.00000570377585646911]
[    0.992401571092335275019]
[    0.992401571092335275019]
[    0.992401571092335275019]
[  2.48710241000629938855e-8]
error: 0.00179806324218628389714
Jx:
[                      -1.0                            0.0                        0.0                         0.0                           0.0  -1.0  -2.0                          0.0                          0.0                        0.0                          0.0                          0.0                      0.0]
[-0.00179972834159425420165        -1000.74836399724196136                        0.0                         0.0                           0.0  -1.0   0.0                          0.0                          0.0                        0.0       


[                      -1.0                            0.0                        0.0                         0.0                          0.0  -1.0  -2.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-0.00179970890130792825494        -1000.74834404588327182                        0.0                         0.0                          0.0  -1.0   0.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-4.72360182756708506396e-7                            0.0    -1000.74834404588327182                         0.0                          0.0   1.0   0.0                          0.0                          0.0                         0.0                         0.0                         0.0                      0.0]
[-4.67785337622334104492e-7   

 [     55.5499744024520169769]
[0.0000998989600483865309403]
[  2.62848663054798608432e-8]
[  2.60315605627894778671e-8]
[-2.53305742690382953853e-10]
[  0.00002630453840697201857]
[ -3.53495213395525282207e-7]
[    0.999998979461341787161]
[      1.0000059710015325049]
[    0.992267703351655824674]
[    0.992267703351655824674]
[    0.992267703351655824674]
[  2.60315605627894778671e-8]
error: 0.00179805364039434546085
Jx:
[                      -1.0                            0.0                        0.0                         0.0                           0.0  -1.0  -2.0                          0.0                         0.0                         0.0                          0.0                          0.0                      0.0]
[ -0.0017997077369804969657         -1000.7483428530058072                        0.0                         0.0                           0.0  -1.0   0.0                          0.0                         0.0                         0.0       

 [     55.5499743694079503855]
[0.0000998989277929524427536]
[  2.63172525163459632794e-8]
[  2.60642633543579167688e-8]
[-2.52989161988046488422e-10]
[0.0000263369488381783107558]
[ -3.53178395702986629217e-7]
[    0.999998977150495832343]
[     1.00000597853169561587]
[    0.992264013249451406812]
[    0.992264013249451406812]
[    0.992264013249451406812]
[  2.60642633543579167688e-8]
error: 0.00179805310663949594835


ValueError: Could not find root within given tolerance. (3.23299e-06 > 2.1684e-19)
Try another starting point or tweak arguments.

In [24]:
factor(diff(sqrt(x)/(1+sqrt(x)), x))

         1          
────────────────────
                   2
    ___ ⎛  ___    ⎞ 
2⋅╲╱ x ⋅⎝╲╱ x  + 1⎠ 

In [3]:
J

⎡     -1                                                   0                  
⎢                                                                             
⎢-18.01528⋅m₁                                        -18.01528⋅n₀             
⎢                                                                             
⎢-18.01528⋅m₂                                              0                  
⎢                                                                             
⎢-18.01528⋅m₃                                              0                  
⎢                                                                             
⎢-18.01528⋅m₄                                              0                  
⎢                                                                             
⎢                                               -18.01528⋅g₂⋅g₃⋅m₂⋅m₃         
⎢     0                                         ──────────────────────        
⎢                                                   

In [36]:
['-log10('+str(X[index]) + '*' + str(X[index + 6]) + ') = ' + 
 str(-log(np.multiply(row*1000, solution[index+6] ))/log(10.0)) \
                                for (index, row) in enumerate(solution) \
                                if index >0 and index < 5]

['-log10(m1*g0) = 1.00677500992410',
 '-log10(m2*g1) = 2.86301445764676',
 '-log10(m3*g2) = 2.88114753833344',
 '-log10(m4*g3) = 11.1178290481576']

In [29]:
[str(X[index]) + ' = ' + str(row) \
                                for (index, row) in enumerate(solution) \
                                if index >4]

['xi1 = 0.00137139594655712',
 'xi2 = -1.00066928308764e-7',
 'g0 = 0.998175405923835',
 'g1 = 1.00031559689023',
 'g2 = 0.959409373322808',
 'g3 = 0.959409373322808',
 'g4 = 0.959409373322808',
 'i = 1.3704036431434e-6']

In [6]:
Matrix([[-1, 0, 0, 0, 0, -1, -2, 0, 0, 0, 0, 0, 0], [-18.01528*m1, -18.01528*n0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0], [-18.01528*m2, 0, -18.01528*n0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [-18.01528*m3, 0, 0, -18.01528*n0, 0, 1, 1, 0, 0, 0, 0, 0, 0], [-18.01528*m4, 0, 0, 0, -18.01528*n0, 0, 1, 0, 0, 0, 0, 0, 0], [0, -18.01528*g2*g3*m2*m3/(g0*g1*m1**2), 18.01528*g2*g3*m3/(g0*g1*m1), 18.01528*g2*g3*m2/(g0*g1*m1), 0, 0, 0, -18.01528*g2*g3*m2*m3/(g0**2*g1*m1), -18.01528*g2*g3*m2*m3/(g0*g1**2*m1), 18.01528*g3*m2*m3/(g0*g1*m1), 18.01528*g2*m2*m3/(g0*g1*m1), 0, 0], [0, 0, 0, 324.5503134784*g3*g4*m4/g0**2, 324.5503134784*g3*g4*m3/g0**2, 0, 0, -649.1006269568*g3*g4*m3*m4/g0**3, 0, 0, 324.5503134784*g4*m3*m4/g0**2, 324.5503134784*g3*m3*m4/g0**2, 0], [0, -18.01528*exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), -18.01528*exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), -18.01528*exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), -18.01528*exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), 0, 0, -1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 100.0*10**(100.0*i)*log(10)], [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i)*(153.0 + 255.0/(31.6227766016838*sqrt(i) + 1)**2 - 8.06380803342937/(sqrt(i)*(31.6227766016838*sqrt(i) + 1)))*log(10)], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i)*(153.0 + 255.0/(31.6227766016838*sqrt(i) + 1)**2 - 8.06380803342937/(sqrt(i)*(31.6227766016838*sqrt(i) + 1)))*log(10)], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i)*(153.0 + 255.0/(31.6227766016838*sqrt(i) + 1)**2 - 8.06380803342937/(sqrt(i)*(31.6227766016838*sqrt(i) + 1)))*log(10)], [0, 0, 0.500000000000000, 0.500000000000000, 0.500000000000000, 0, 0, 0, 0, 0, 0, 0, -1]])

⎡     -1                                                   0                  
⎢                                                                             
⎢-18.01528⋅m₁                                        -18.01528⋅n₀             
⎢                                                                             
⎢-18.01528⋅m₂                                              0                  
⎢                                                                             
⎢-18.01528⋅m₃                                              0                  
⎢                                                                             
⎢-18.01528⋅m₄                                              0                  
⎢                                                                             
⎢                                               -18.01528⋅g₂⋅g₃⋅m₂⋅m₃         
⎢     0                                         ──────────────────────        
⎢                                                   

In [7]:
simplify(10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i)*(153.0 + 255.0/(31.6227766016838*sqrt(i) + 1)**2 - 8.06380803342937/(sqrt(i)*(31.6227766016838*sqrt(i) + 1)))*log(10))

                             ___                                              
    -16.1276160668587⋅(-1)⋅╲╱ i                                               
  - ──────────────────────────── + 153.0⋅i                                    
                        ___                                                   
     31.6227766016838⋅╲╱ i  + 1            ⎛                    255.0         
10                                        ⋅⎜153.0 + ──────────────────────────
                                           ⎜                                  
                                           ⎜        ⎛                   ___   
                                           ⎝        ⎝31.6227766016838⋅╲╱ i  + 

                                                 
                                                 
                                                 
                                                 
            -8.06380803342937⋅(-1)      ⎞        
─── - ────────────────────────────────

In [8]:
simplify(j_10_13)

              ___           ⎛  ___    ⎞                                       
  - - -0.51⋅╲╱ i  + 0.153⋅i⋅⎝╲╱ i  + 1⎠                                       
  ─────────────────────────────────────                                       
                  ___                   ⎛                                   2 
                ╲╱ i  + 1               ⎜                    ___ ⎛  ___    ⎞  
10                                     ⋅⎝0.352295519228089⋅╲╱ i ⋅⎝╲╱ i  + 1⎠  
──────────────────────────────────────────────────────────────────────────────
                                                         2                    
                                          ___ ⎛  ___    ⎞                     
                                        ╲╱ i ⋅⎝╲╱ i  + 1⎠                     

                    
                    
                    
                   ⎞
                   ⎟
- 0.587159198713482⎠
────────────────────
                    
                    
                    

In [9]:
j_10_13

              ___                                                       
    - -0.51⋅╲╱ i                                                        
  - ────────────── + 0.153⋅i                                            
        ___                                                             
      ╲╱ i  + 1              ⎛                    - -0.587159198713482 ⎞
10                          ⋅⎜0.352295519228089 - ─────────────────────⎟
                             ⎜                                       2 ⎟
                             ⎜                        ___ ⎛  ___    ⎞  ⎟
                             ⎝                      ╲╱ i ⋅⎝╲╱ i  + 1⎠  ⎠

In [10]:
diff(10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)), i)

                             ___                                              
    -16.1276160668587⋅(-1)⋅╲╱ i                                               
  - ──────────────────────────── + 153.0⋅i                                    
                        ___                                                   
     31.6227766016838⋅╲╱ i  + 1            ⎛                    255.0         
10                                        ⋅⎜153.0 + ──────────────────────────
                                           ⎜                                  
                                           ⎜        ⎛                   ___   
                                           ⎝        ⎝31.6227766016838⋅╲╱ i  + 

                                                 
                                                 
                                                 
                                                 
            -8.06380803342937⋅(-1)      ⎞        
─── - ────────────────────────────────

In [22]:
factor((log(10)*-0.510*(-0.3/m0_ref) + 
         log(10)*-0.510/(m0_ref)/(2*sqrt(i/m0_ref)*(1+sqrt(i/m0_ref))**2)) * 
        10**(-0.510*(-1)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)))

                                 ___                                          
        -16.1276160668587⋅(-1)⋅╲╱ i                                           
      - ──────────────────────────── + 153.0⋅i                                
                            ___                                               
         31.6227766016838⋅╲╱ i  + 1            ⎛          3/2           ___   
1.0⋅10                                        ⋅⎝153000.0⋅i    + 153.0⋅╲╱ i  + 
──────────────────────────────────────────────────────────────────────────────
                                                                              
                                             ___ ⎛                   ___      
                                           ╲╱ i ⋅⎝31.6227766016838⋅╲╱ i  + 1.0

                                              
                                              
                                              
                                              
                     

In [12]:
factor(diff(10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)), i))

                                 ___                                          
        -16.1276160668587⋅(-1)⋅╲╱ i                                           
      - ──────────────────────────── + 153.0⋅i                                
                            ___                                               
         31.6227766016838⋅╲╱ i  + 1            ⎛          3/2           ___   
1.0⋅10                                        ⋅⎝153000.0⋅i    + 153.0⋅╲╱ i  + 
──────────────────────────────────────────────────────────────────────────────
                                                                              
                                             ___ ⎛                   ___      
                                           ╲╱ i ⋅⎝31.6227766016838⋅╲╱ i  + 1.0

                                              
                                              
                                              
                                              
                     

In [4]:
f_val = [f_eval.subs(dict([(key, X0[index]) for (index, key) in enumerate(X)])).evalf() for f_eval in f_0]

[7.105427357601e-15, 7.48804288100424e-5, -2.22044604479111e-23, 7.48804288100
396e-11, 7.48804288100396e-11, -3.1621604814443e-7, -2.44160386651602e-20, -0.
00179856425917424, 2.30086222398356e-8, -0.000370991781870158, -0.000370991781
870158, -0.000370991781870158, 1.29246970711411e-26]

In [3]:
dict([(key, X0[index]) for (index, key) in enumerate(X)])

{g₀: 1.0, g₁: 1.0, g₂: 1.0, g₃: 1.0, g₄: 1.0, i: 9.99251756e-11, m₁: 9.9925175
6e-05, m₂: 2.21878461e-26, m₃: 9.99251756e-11, m₄: 9.99251756e-11, n₀: 55.55, 
ξ₁: 0.0, ξ₂: 0.0}

In [27]:
x_val = Matrix([5.55500000e+01,   9.99251756e-05,   2.21878461e-26,
           9.99251756e-11,   9.99251756e-11,   0.00000000e+00,
           0.00000000e+00,   1.00000000e+00,   1.00000000e+00,
           1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
           9.99251756e-11])
x_val = Matrix([5.55499999e+01,   9.99248539e-05,   3.21929919e-10,
           3.23450589e-10,   1.52067039e-12,   3.22170981e-07,
          -9.84781910e-08,   9.99999998e-01,   1.00000005e+00,
           9.99650674e-01,   9.99650674e-01,   9.99650674e-01,
           3.23450589e-10])
x_val = Matrix([5.55499996e+01,   9.99245297e-05,   6.46769017e-10,
           6.46770648e-10,   1.63055884e-15,   6.47253317e-07,
          -9.99983683e-08,   9.99999992e-01,   1.00000013e+00,
           9.99317591e-01,   9.99317591e-01,   9.99317591e-01,
           6.46770648e-10])
x_val = Matrix([  5.55499989e+01,   9.99238840e-05,   1.29362717e-09,   1.29362717e-09,
   8.73620108e-18,   1.29459582e-06,  -9.99999913e-08,   9.99999979e-01,
   1.00000027e+00,   9.98846754e-01,   9.98846754e-01,   9.98846754e-01,
   1.29362717e-09])
f_val = Matrix([f_eval.subs(dict([(key, x_val[index]) for (index, key) in enumerate(X)])).evalf() for f_eval in f_0])
f_val

⎡ 5.40416834927987e-9 ⎤
⎢                     ⎥
⎢ 7.48803803177106e-5 ⎥
⎢                     ⎥
⎢2.43615633003754e-15 ⎥
⎢                     ⎥
⎢7.48915361564575e-11 ⎥
⎢                     ⎥
⎢7.48803572574078e-11 ⎥
⎢                     ⎥
⎢-3.16215747129814e-7 ⎥
⎢                     ⎥
⎢-3.26506047459702e-18⎥
⎢                     ⎥
⎢-0.00179856296488412 ⎥
⎢                     ⎥
⎢ 2.78687082028872e-8 ⎥
⎢                     ⎥
⎢-0.000179535026754946⎥
⎢                     ⎥
⎢-0.000179535026754946⎥
⎢                     ⎥
⎢-0.000179535026754946⎥
⎢                     ⎥
⎣   4.36810054e-18    ⎦

In [22]:
f_val.T * f_val

[3.54347883678728e-6]

In [25]:
f_val.T * f_val

[3.44413140341052e-6]

In [ ]:
f_val.T * f_val