# ref. Mortimer S. 271
$$
\begin{align}
HA + H2O & \rightleftharpoons H3O(+) + A(-) & K= & 1.75\times 10^{-5} \\
2 H2O & \rightleftharpoons H3O(+) + OH(-) & K= & 10^{-14}
\end{align} \\
$$
<pre>
```
| i | comp. | m0, mol/g |
|---|-------|-----------|
|0|H2O	|	0.05555
|1|HA	|	0.000100
|2|A(-)	|	0.0
|3|H3O(+)|	1.0E-10
|4|HO(-)|	1.0E-10
```
</pre>
$$x = [n_0 m_1 m_2 m_3 m_4 \xi_1 \xi_2 \gamma_0 \gamma_1 \gamma_3 \gamma_4]$$

In [1]:
from sympy import *
import numpy as np
init_printing(use_unicode = True)
eps = np.finfo(float).eps
mm0 = 2*1.00794+15.9994
m0_ref = 1/1000.0
x, n0, m1, m2, m3, m4 = symbols('x n0 m1 m2 m3 m4')
xi1, xi2 = symbols('xi1 xi2')
g0, g1, g2, g3, g4 = symbols('g0 g1 g2 g3 g4')
i = symbols('i')
X0 = (55.5486293302,0.0000985577634614,0.00000136987783435,0.0000013698778423,7.94928842737e-15,
      0.00137086977796, -9.99920449554e-08,
      0.998176760953, 1.00031547577, 0.959416637324, 0.959416637324, 0.959416637324, 
      0.0000013698778423) #1/2.0*(0.0 + 10e-10*(+1)**2 + 10e-10*(-1)**2)
X = (n0, m1, m2, m3, m4,
     xi1, xi2,
     g0, g1, g2, g3, g4, i)
Q1 = 1 * g0**-1 * g1**-1 * g2**1 * g3**1 * g4**0 * \
        (1/mm0)**-1 * m1**-1 * m2**1 * m3**1 * m4**0 * \
        (1/m0_ref)**(-1-1+1+1+0)
Q2 = 1 * g0**-2 * g1**0 * g2**0 * g3**1 * g4**1 * \
        (1/mm0)**-2 * m1**0 * m2**0 * m3**1 * m4**1 * \
        (1/m0_ref)**(-2+0+0+1+1)
f_0 = (
    -n0 + 0.05555*1000 - 2*xi2 - 1*xi1,
    -m1*n0*mm0 + 0.0001*(0.05555*1000)*mm0 -xi1,
    -m2*n0*mm0 + 0*(0.05555*1000)*mm0 +xi1,
    -m3*n0*mm0 + 1.0E-10*(0.05555*1000)*mm0 +xi1 + xi2,
    -m4*n0*mm0 + 1.0E-10*(0.05555*1000)*mm0 + xi2,
    -10**-4.75696195131371/(997/mm0) + Q1,
    -10**-14/(997/mm0)**2 + Q2,
    -g0 + exp(-1.0*mm0*(m1+ m2 + m3 + m4)),
    -g1 + 10**(0.1*i/m0_ref),
    -g2 + 10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)),
    -g3 + 10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)),
    -g4 + 10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)),
    -i + 1/2.0*(m2*(-1)**2 + m3*(+1)**2 + m4*(-1)**2)
    )
j_8_2 = -1.0*mm0*exp(-1.0*mm0*(m1 + m2 + m3 + m4))
j_8_3 = j_8_2
j_8_4 = j_8_2
j_8_5 = j_8_2
factor_1 = (sqrt(i)/(1 + sqrt(i))-0.3*i)
dfactor_1_di = (1/(2 * sqrt(i) * (1 + sqrt(i))**2)-0.3) 
j_9_13 =  0.1*10**(-0.1*i)
j_10_13 = (-0.510*log(10.0)*(-1)**2*dfactor_1_di) * \
          10**(-0.510*(-1)**2*factor_1)
j_11_13 = (-0.510*log(10.0)*(+1)**2*dfactor_1_di) * \
          10**(-0.510*(+1)**2*factor_1)
j_12_13 = (-0.510*log(10.0)*(-1)**2*dfactor_1_di) * \
          10**(-0.510*(-1)**2*factor_1)

J = Matrix((
    (-1, 0, 0, 0, 0,            -1, -2, 0, 0, 0, 0, 0, 0),
    (-m1*mm0, -n0*mm0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0),
    (-m2*mm0, 0, -n0*mm0, 0, 0, +1, 0, 0, 0, 0, 0, 0, 0),
    (-m3*mm0, 0, 0, -n0*mm0, 0, +1, +1, 0, 0, 0, 0, 0, 0),
    (-m4*mm0, 0, 0, 0, -n0*mm0,  0, +1, 0, 0, 0, 0, 0, 0),
    (0,             -1/m1*Q1, +1/m2*Q1, +1/m3*Q1,  0/m4*Q1, 0, 0, 
        -1/g0*Q1,   -1/g1*Q1, +1/g2*Q1, +1/g3*Q1,  0/g4*Q1, 0),
    (0,              0/m1*Q2,  0/m2*Q2, +1/m3*Q2, +1/m4*Q2, 0, 0, 
        -2/g0*Q1,    0/g1*Q2,  0/g2*Q2, +1/g3*Q1, +1/g4*Q2, 0),
    (0,  j_8_2, j_8_3, j_8_4, j_8_5, 0, 0, 
                          -1, 0, 0, 0, 0, 0),
    (0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, j_9_13),
    (0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, j_10_13),
    (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, j_11_13),
    (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, j_12_13),
    (0, 0, 1/2.0*(-1)**2, 1/2.0*(+1)**2, 1/2.0*(-1)**2, 
                    0, 0, 0, 0, 0, 0, 0, -1)
    ))
solution = nsolve(f_0, X, X0, verbose=True)

f(x):
Matrix([[-n0 - xi1 - 2*xi2 + 55.55, -18.01528*m1*n0 - xi1 + 0.1000748804, -18.01528*m2*n0 + xi1, -18.01528*m3*n0 + xi1 + xi2 + 1.000748804e-7, -18.01528*m4*n0 + xi2 + 1.000748804e-7, -3.1621604814443e-7 + 18.01528*g2*g3*m2*m3/(g0*g1*m1), -3.26506413401086e-18 + 324.5503134784*g3*g4*m3*m4/g0**2, -g0 + exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), 10**(100.0*i) - g1, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i) - g2, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i) - g3, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i) - g4, -i + 0.5*m2 + 0.5*m3 + 0.5*m4]])
J(x):
Matrix([[-1, 0, 0, 0, 0, -1, -2, 0, 0, 0, 0, 0, 0], [-18.01528*m1, -18.01528*n0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0], [-18.01528*m2, 0, -18.01528*n0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [-18.01528*m3, 0, 0, -18.01528*n0, 0, 1, 1, 0, 0, 0, 0, 0, 0], [-18.01528*m4, 0, 0, 0, -18.01528*n0, 0, 1, 0, 0, 0, 0, 0, 0], [0, -18.01528*g2*g3*m2*m3/(g0*


Jx:


[                        -1.0                         0.0                      0.0                         0.0                         0.0  -1.0  -2.0                          0.0                         0.0                        0.0                         0.0                         0.0                      0.0]
[  -0.00177554570493089026876     -1000.72411099976550357                      0.0                         0.0                         0.0  -1.0   0.0                          0.0                         0.0                        0.0                         0.0                         0.0                      0.0]
[-0.0000246787327516088690157                         0.0  -1000.72411099976550357                         0.0                         0.0   1.0   0.0                          0.0                         0.0                        0.0                         0.0                         0.0                      0.0]
[-0.0000246787328948303429602                   


[                        -1.0                         0.0                      0.0                         0.0                         0.0  -1.0  -2.0                          0.0                         0.0                        0.0                        0.0                        0.0                      0.0]
[  -0.00177688426480119584866     -1000.72410152349935647                      0.0                         0.0                         0.0  -1.0   0.0                          0.0                         0.0                        0.0                        0.0                        0.0                      0.0]
[-0.0000246882052010929932328                         0.0  -1000.72410152349935647                         0.0                         0.0   1.0   0.0                          0.0                         0.0                        0.0                        0.0                        0.0                      0.0]
[-0.0000246882053442484843289                         

In [2]:
factor(diff(sqrt(x)/(1+sqrt(x)), x))

         1          
────────────────────
                   2
    ___ ⎛  ___    ⎞ 
2⋅╲╱ x ⋅⎝╲╱ x  + 1⎠ 

In [3]:
J

⎡     -1                                                   0                  
⎢                                                                             
⎢-18.01528⋅m₁                                        -18.01528⋅n₀             
⎢                                                                             
⎢-18.01528⋅m₂                                              0                  
⎢                                                                             
⎢-18.01528⋅m₃                                              0                  
⎢                                                                             
⎢-18.01528⋅m₄                                              0                  
⎢                                                                             
⎢                                               -18.01528⋅g₂⋅g₃⋅m₂⋅m₃         
⎢     0                                         ──────────────────────        
⎢                                                   

In [4]:
['-log10('+str(X[index]) + ') = ' + str(-log(row*1000)/log(10.0)) \
                                for (index, row) in enumerate(solution) \
                                if index >0 and index < 5]

['-log10(m1) = 1.00598187499021',
 '-log10(m2) = 2.86315149801107',
 '-log10(m3) = 2.86315149549280',
 '-log10(m4) = 11.0998330053170']

In [5]:
[str(X[index]) + ' = ' + str(row) \
                                for (index, row) in enumerate(solution) \
                                if index >4]

['xi1 = 0.00137139594655712',
 'xi2 = -1.00066928308764e-7',
 'g0 = 0.998175405923835',
 'g1 = 1.00031559689023',
 'g2 = 0.959409373322808',
 'g3 = 0.959409373322808',
 'g4 = 0.959409373322808',
 'i = 1.3704036431434e-6']

In [6]:
Matrix([[-1, 0, 0, 0, 0, -1, -2, 0, 0, 0, 0, 0, 0], [-18.01528*m1, -18.01528*n0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0], [-18.01528*m2, 0, -18.01528*n0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [-18.01528*m3, 0, 0, -18.01528*n0, 0, 1, 1, 0, 0, 0, 0, 0, 0], [-18.01528*m4, 0, 0, 0, -18.01528*n0, 0, 1, 0, 0, 0, 0, 0, 0], [0, -18.01528*g2*g3*m2*m3/(g0*g1*m1**2), 18.01528*g2*g3*m3/(g0*g1*m1), 18.01528*g2*g3*m2/(g0*g1*m1), 0, 0, 0, -18.01528*g2*g3*m2*m3/(g0**2*g1*m1), -18.01528*g2*g3*m2*m3/(g0*g1**2*m1), 18.01528*g3*m2*m3/(g0*g1*m1), 18.01528*g2*m2*m3/(g0*g1*m1), 0, 0], [0, 0, 0, 324.5503134784*g3*g4*m4/g0**2, 324.5503134784*g3*g4*m3/g0**2, 0, 0, -649.1006269568*g3*g4*m3*m4/g0**3, 0, 0, 324.5503134784*g4*m3*m4/g0**2, 324.5503134784*g3*m3*m4/g0**2, 0], [0, -18.01528*exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), -18.01528*exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), -18.01528*exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), -18.01528*exp(-18.01528*m1 - 18.01528*m2 - 18.01528*m3 - 18.01528*m4), 0, 0, -1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 100.0*10**(100.0*i)*log(10)], [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i)*(153.0 + 255.0/(31.6227766016838*sqrt(i) + 1)**2 - 8.06380803342937/(sqrt(i)*(31.6227766016838*sqrt(i) + 1)))*log(10)], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i)*(153.0 + 255.0/(31.6227766016838*sqrt(i) + 1)**2 - 8.06380803342937/(sqrt(i)*(31.6227766016838*sqrt(i) + 1)))*log(10)], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i)*(153.0 + 255.0/(31.6227766016838*sqrt(i) + 1)**2 - 8.06380803342937/(sqrt(i)*(31.6227766016838*sqrt(i) + 1)))*log(10)], [0, 0, 0.500000000000000, 0.500000000000000, 0.500000000000000, 0, 0, 0, 0, 0, 0, 0, -1]])

⎡     -1                                                   0                  
⎢                                                                             
⎢-18.01528⋅m₁                                        -18.01528⋅n₀             
⎢                                                                             
⎢-18.01528⋅m₂                                              0                  
⎢                                                                             
⎢-18.01528⋅m₃                                              0                  
⎢                                                                             
⎢-18.01528⋅m₄                                              0                  
⎢                                                                             
⎢                                               -18.01528⋅g₂⋅g₃⋅m₂⋅m₃         
⎢     0                                         ──────────────────────        
⎢                                                   

In [7]:
simplify(10**(-16.1276160668587*sqrt(i)/(31.6227766016838*sqrt(i) + 1) + 153.0*i)*(153.0 + 255.0/(31.6227766016838*sqrt(i) + 1)**2 - 8.06380803342937/(sqrt(i)*(31.6227766016838*sqrt(i) + 1)))*log(10))

                             ___                                              
    -16.1276160668587⋅(-1)⋅╲╱ i                                               
  - ──────────────────────────── + 153.0⋅i                                    
                        ___                                                   
     31.6227766016838⋅╲╱ i  + 1            ⎛                    255.0         
10                                        ⋅⎜153.0 + ──────────────────────────
                                           ⎜                                  
                                           ⎜        ⎛                   ___   
                                           ⎝        ⎝31.6227766016838⋅╲╱ i  + 

                                                 
                                                 
                                                 
                                                 
            -8.06380803342937⋅(-1)      ⎞        
─── - ────────────────────────────────

In [8]:
simplify(j_10_13)

              ___           ⎛  ___    ⎞                                       
  - - -0.51⋅╲╱ i  + 0.153⋅i⋅⎝╲╱ i  + 1⎠                                       
  ─────────────────────────────────────                                       
                  ___                   ⎛                                   2 
                ╲╱ i  + 1               ⎜                    ___ ⎛  ___    ⎞  
10                                     ⋅⎝0.352295519228089⋅╲╱ i ⋅⎝╲╱ i  + 1⎠  
──────────────────────────────────────────────────────────────────────────────
                                                         2                    
                                          ___ ⎛  ___    ⎞                     
                                        ╲╱ i ⋅⎝╲╱ i  + 1⎠                     

                    
                    
                    
                   ⎞
                   ⎟
- 0.587159198713482⎠
────────────────────
                    
                    
                    

In [9]:
j_10_13

              ___                                                       
    - -0.51⋅╲╱ i                                                        
  - ────────────── + 0.153⋅i                                            
        ___                                                             
      ╲╱ i  + 1              ⎛                    - -0.587159198713482 ⎞
10                          ⋅⎜0.352295519228089 - ─────────────────────⎟
                             ⎜                                       2 ⎟
                             ⎜                        ___ ⎛  ___    ⎞  ⎟
                             ⎝                      ╲╱ i ⋅⎝╲╱ i  + 1⎠  ⎠

In [10]:
diff(10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)), i)

                             ___                                              
    -16.1276160668587⋅(-1)⋅╲╱ i                                               
  - ──────────────────────────── + 153.0⋅i                                    
                        ___                                                   
     31.6227766016838⋅╲╱ i  + 1            ⎛                    255.0         
10                                        ⋅⎜153.0 + ──────────────────────────
                                           ⎜                                  
                                           ⎜        ⎛                   ___   
                                           ⎝        ⎝31.6227766016838⋅╲╱ i  + 

                                                 
                                                 
                                                 
                                                 
            -8.06380803342937⋅(-1)      ⎞        
─── - ────────────────────────────────

In [22]:
factor((log(10)*-0.510*(-0.3/m0_ref) + 
         log(10)*-0.510/(m0_ref)/(2*sqrt(i/m0_ref)*(1+sqrt(i/m0_ref))**2)) * 
        10**(-0.510*(-1)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)))

                                 ___                                          
        -16.1276160668587⋅(-1)⋅╲╱ i                                           
      - ──────────────────────────── + 153.0⋅i                                
                            ___                                               
         31.6227766016838⋅╲╱ i  + 1            ⎛          3/2           ___   
1.0⋅10                                        ⋅⎝153000.0⋅i    + 153.0⋅╲╱ i  + 
──────────────────────────────────────────────────────────────────────────────
                                                                              
                                             ___ ⎛                   ___      
                                           ╲╱ i ⋅⎝31.6227766016838⋅╲╱ i  + 1.0

                                              
                                              
                                              
                                              
                     

In [12]:
factor(diff(10**(-0.510*(-1.0)**2*(sqrt(i/m0_ref)/(1+sqrt(i/m0_ref))-0.3*i/m0_ref)), i))

                                 ___                                          
        -16.1276160668587⋅(-1)⋅╲╱ i                                           
      - ──────────────────────────── + 153.0⋅i                                
                            ___                                               
         31.6227766016838⋅╲╱ i  + 1            ⎛          3/2           ___   
1.0⋅10                                        ⋅⎝153000.0⋅i    + 153.0⋅╲╱ i  + 
──────────────────────────────────────────────────────────────────────────────
                                                                              
                                             ___ ⎛                   ___      
                                           ╲╱ i ⋅⎝31.6227766016838⋅╲╱ i  + 1.0

                                              
                                              
                                              
                                              
                     